### ISSUE TITLE
Assignments with Overall grade set to none

### ISSUE THREAD

**Issue by angemmell** [jmcgettrick/moodle-mod_turnitintooltwo#41]
In a Turnitin assignment settings where the overall grade is set to NONE, the Turnitin assignment 
does not appear in the Grades area.

I have not seen this happened before, please let me know if this is something new. 
Regards
Anna

**Comment by jmcgettrick** [comment]
Hi, we removed this in in a recent update for Direct Assignments as in that instance they can not be graded. We are aware though that other modules are included in the gradebook if their overall grade is set to NONE.

**Comment by jmcgettrick** [comment]
On further investigation it appears that Moodle assignments add a column to the gradebook if overall grade is set to 'None' because there are other feedback types available to the assignment. If all of those are turned off then there is no entry in the gradebook. A Turnitin Assignment only has Grademark to provide feedback so if there is no grading we don't need an entry in the gradebook.
