### ISSUE TITLE
Plugin retrieving students with deleted flag in database

### ISSUE THREAD

**Issue by daparker26** [jmcgettrick/moodle-mod_turnitintooltwo#58]
Hi John,

I'm having an issue, and it may be difficult to recreate, with the Turnitin Assignment enrolling deleted student accounts. We are in the process of using LDAP in place of manual accounts and I think if Moodle sees a userid with a manual account that is now being authenticated with LDAP, it doesn't delete or update the account in the database, but rather places a "1" in the deleted column and then created a new account for that user.

This isn't a big deal because Moodle and Moodle activities ignore students with a "1" in the deleted account; however, the Turnitin assignment is picking it up when a student who has two accounts in the database is in the course. In the Turnitin assignment, it shows the user with their current account, and then it shows a duplicate user with the caption (non-enrolled user). The times I have seen this, the student submits a paper, it submits under the "non-enrolled user", which the teacher can see, but it doesn't submit under the student's active account. Therefore, to the student, after it submits, they do not see that it has submitted, and still have the option to submit a paper.

Also, even after deleting the duplicate accounts in the database, Turnitin still picks up two accounts (I'm assuming because it was already synced to the Turnitin servers).

Let me know if there is additional information I can provide.

I am using Moodle 2.8.6 and turnitintooltwo v2015040109 (also had issues on 2015040105).

**Comment by jmcgettrick** [comment]
We had fixed this in 2015040106 with this commit: https://github.com/jmcgettrick/moodle-mod_turnitintooltwo/commit/532aa5743acdf34bdd00ea423c03910680063cee. It was occuring when a submission was refreshed it was being assigned to a deleted user because that was the first user the plugin found in the database when turnitintooltwo_user->get_moodle_user_id() was called. Is it still occuring in v2015040109?

**Comment by daparker26** [comment]
We were on v2015040105 and that is when I noticed the issue. I upgraded to v2015040109, but the assignments were created and students were enrolled in the course while we were still on v2015040105. After the upgrade, the Turnitin Assignments in that particular course are still enrolling deleted users, even after I go into the "Turnitin Students" tab, remove the deleted users, and click "Enrol All Students". 

I

**Comment by jmcgettrick** [comment]
I'll need to investigate this a bit more as I can't pinpoint the exact cause but it's to do with the deleted user not being unenrolled from Turnitin. I'm assuming this is occuring because a deleted Moodle user and new Moodle user have the same email address?

As an additional point when investigating this, I've found that the enrol all students link is querying the Turnitin API first to see who is enrolled on the Turnitin side. This looks to be a pointless exercise though as it doesn't remove any users who aren't in Moodle. Therefore, the deleted users will appear in the inbox as non-enrolled users.

We'll get this fixed so that "enrol all students" doesn't query Turnitin first as it really isn't necessary and only adds to the time the process takes.

**Comment by jmcgettrick** [comment]
As well as this, you could try unlinking the deleted users in the plugin configuration area which would remove their Turnitin id from the plugin database tables.

**Comment by daparker26** [comment]
Thanks John. I'll try that and see how it goes. As always, I appreciate you looking into this.

**Comment by jmcgettrick** [comment]
No problem @daparker26 - I'm closing this issue for now as the repository is moving to the Turnitin account. Can you raise it there: https://github.com/turnitin/moodle-mod_turnitintooltwo if it's ongoing? 

Cheers
